### PR TITLE
Use code blocks with syntax highlighting

### PR DESCRIPTION
**Pull request by hluk**
Signed-off-by: Lukas Holecek <hluk@email.cz>

### CODE REVIEW

**Comment by ralphbean** [comment]
@hluk when I try this on our confluence instance as a test, I get the following error displayed *in* the confluence page:

```
 Error rendering macro 'code': Invalid value specified for parameter 'com.atlassian.confluence.ext.code.render.InvalidValueException'
```

**Comment by ralphbean** [comment]
Oh, I take that back.  I only get the error if I do not specify the `language` for a triple-quoted code block.

I.e., using \`\`\`bash works but using just plain \`\`\` does not.

Can you try to fix that before we merge?

**Comment by hluk** [comment]
Fixed. I'll post a PR to add tests later.

**Comment by ralphbean** [comment]
Tested locally - looks awesome.

**Pull request merged**
